module.exports = `
S -> CODE_BLOCK

CODE_BLOCK -> FUNC CODE_BLOCK | LAMBDA

FUNC -> function FUNC_NAME PARAMETER do ; EXPRESSION_BLOCK end ;
PARAMETER -> with input PARAM_NAME PARAMETER' | LAMBDA
PARAMETER' -> VARIABLE PARA METER' | LAMBDA

EXPRESSION_BLOCK -> EXPRESSION ; EXPRESSION_BLOCK | LAMBDA

EXPRESSION -> SET | RETURN | WHILE | SHOW
SET -> set VARIABLE equal VALUE_GET
SHOW -> show VALUE_GET
RETURN -> VALUE_GET

WHILE -> while CONDITION do ; EXPRESSION_BLOCK end ;
CONDITION -> VALUE_GET COMPARATOR VALUE_GET
COMPARATOR -> less than | more than | equal

VALUE_GET -> ARITHMETIC_EQUATION | FUNCTION_CALL | string STRING
STRING -> ANY STRING | LAMBDA

FUNCTION_CALL -> FUNC_NAME PARAMS
PARAMS -> PARAMS' PARAMS | LAMBDA
PARAMS' -> NUMBER | VARIABLE

ARITHMETIC_EQUATION -> NUMBER OPERATOR ARITHMETIC_EQUATION | NUMBER
OPERATOR -> plus | minus | multiply | devide | power
`;

export default module.exports;